const words = {
  english: {
    addDefect: "Add Defect",
    area: "Area",
    defectDescription: "Defect Description",
    selectPhoto: "Select a photo from the library or take a new photo",
    chooseOption: "Choose an option",
    camera: "Camera",
    library: "Library",
    cancel: "Cancel",
    close: "Close",
    modalTitleColor: "Color Information",
    modalYellow: "Yellow: Whole Project Progress",
    modalGreen: "Green: Completed",
    completed: "Completed",
    pending: "Pending",
    modalOrange: "Orange: Risky/Uncompleted",
    modalGray: "Gray: Upcoming",
    error: "Error",
    noDescription: "Description can't be empty",
    noImageSelected: "No image selected.",
    noAreaSelected: "No area selected.",
    success: "Success",
    imageUploaded: "Image uploaded successfully!",
    uploadFailed: "Failed to upload image.",
    cameraPermissionError:
      "Sorry, we need camera permissions to make this work!",
    mediaLibraryPermissionError:
      "Sorry, we need media library permissions to make this work!",
    selectImage: "Select Image",
    confirm: "Confirm",
    selectArea: "Select Area",
    productNo: "Product No",
    price: "Price",
    spec: "Spec.(mm)",
    quantity: "Quantity",
    modalTitleMilestone: "Add a Task",
    modalTitle: "Select an Order Option",
    modalOption1: "Confirmation Order",
    modalOption2: "Variable Order",
    errorNoSelect: "Invalid Selection",
    errorNoSelect1: "Please select at least one product with a quantity.",
    none: "There are no Confirmation Records available.",
    noneVariableOrder: "There are no Variable Orders available.",
    noneMilestone: "There are no Milestones available.",
    noneDefects: "There are no Defects available.",
    noneContacts: "There are no Contacts available.",
    productStatus: "Product Status",
    photo: "Photo",
    productDescription: "Product Description",
    orderStatus: "Order Status",
    deliveryStatus: "Delivery Status",
    uploadImageFor: "Upload Image for ",
    uploadedImageFor: "Uploaded Image for ",
    connectionError:
      "No response received from server. Please check your connection.",
    imageLoadError: "An error occurred while loading images.",
    search: "Search...",
    selectStartDate: "Select Start Date",
    selectEndDate: "Select End Date",
    addProject: "Add Project",
    title: "Add New Project",
    milestoneTitle: "Milestone",
    projectName: "Project Name",
    quoteeName: "Quotee Name",
    quoteeMobile: "Quotee Mobile",
    quoteeEmail: "Quotee Email",
    companyName: "Company Name",
    district: "District",
    days: "days",
    street: "Street",
    floorUnit: "Floor Unit",
    startDate: "Start Date:",
    endDate: "End Date:",
    candidateMaterials: "Candidate Materials",
    confirmationRecord: "Confirmation Record",
    variableOrder: "Variable Order",
    successCandidate: "Products selected successfully!",
    milestone: "Milestone",
    defects: "Defects",
    contact: "Contacts",
    placeholder: "Task Description",
    noneTasks: "There are no tasks available.",
    addTask: "Add Task",
    modalTitleTask: "Add Task",
    taskDescription: "Task Description:",
    errorNoSelect2: "Please select at least one product with a quantity.",
    ownerName: "Owner Name:",
    projectDetails: "Project Details",
    tel: "Tel:",
    phoneNumber: "Contact Number:",
    emailAddress: "Email Address:",
    modalTitleCategory: "Add Category",
    modalPlaceholderCategory: "Enter category name",
    modalConfirmCategory: "Confirm",
    modalCancelCategory: "Cancel",
    progress: "Progress",
    blueprint: "Blueprint",
    beforePic: "Before Repair Picture",
    afterPic: "After Repair Picture",
    defectStatus: "Defect Status",
    roleManagementTeam: "Management Team",
    roleProjectManager: "Project Manager",
    roleAdmin: "Admin",
    roleSubcontractor: "Subcontractor",
    errorCandidate: "Failed to select products.",
  },
  chinese: {
    addDefect: "加入缺陷",
    errorCandidate: "未能選擇產品.",
    successCandidate: "產品成功揀選!",
    phoneNumber: "聯絡電話:",
    emailAddress: "電郵地址:",
    roleManagementTeam: "管理團隊",
    roleProjectManager: "項目管理員",
    roleAdmin: "管理員",
    roleSubcontractor: "分包商",
    area: "區域",
    defectDescription: "缺陷描述",
    selectPhoto: "從相簿選擇照片或拍攝新照片",
    chooseOption: "選擇一個選項",
    camera: "相機",
    library: "相簿",
    cancel: "取消",
    close: "關閉",
    modalTitleColor: "顏色資訊",
    modalYellow: "黃色: 整個項目進度",
    modalGreen: "綠色: 已完成",
    completed: "完成",
    pending: "待處理",
    modalOrange: "橙色: 有風險/未完成",
    modalGray: "灰色: 即將來臨",
    error: "錯誤",
    noDescription: "描述不能為空",
    noImageSelected: "未選擇圖片.",
    noAreaSelected: "未選擇區域.",
    success: "成功",
    imageUploaded: "圖片上傳成功！",
    uploadFailed: "圖片上傳失敗.",
    cameraPermissionError: "抱歉，我們需要相機權限才能正常運行！",
    mediaLibraryPermissionError: "抱歉，我們需要媒體庫權限才能正常運行！",
    selectImage: "選擇圖片",
    confirm: "確認",
    selectArea: "選擇區域",
    productNo: "產品編號",
    price: "價格",
    spec: "規格（mm）",
    quantity: "數量",
    modalTitleMilestone: "添加任務",
    modalTitle: "選擇訂單選項",
    modalOption1: "確認訂單",
    modalOption2: "可變訂單",
    errorNoSelect: "無效的選擇",
    errorNoSelect1: "請選擇至少一個有數量的產品.",
    none: "沒有可用的確認記錄.",
    noneVariableOrder: "沒有可用的變量訂單.",
    noneMilestone: "沒有可用的里程碑.",
    noneDefects: "沒有可用的缺陷.",
    noneContacts: "沒有可用的聯絡人.",
    productStatus: "產品狀態",
    photo: "照片",
    productDescription: "產品描述",
    orderStatus: "訂單狀態",
    deliveryStatus: "送貨狀態",
    uploadImageFor: "上傳圖片以便",
    uploadedImageFor: "已上傳的圖片",
    connectionError: "未收到伺服器回應.請檢查您的連接.",
    imageLoadError: "加載圖片時出現錯誤.",
    search: "搜尋...",
    selectStartDate: "選擇開始日期",
    selectEndDate: "選擇結束日期",
    addProject: "添加項目",
    title: "添加新項目",
    milestoneTitle: "里程碑",
    projectName: "項目名稱",
    quoteeName: "報價者名稱",
    quoteeMobile: "報價者手機",
    quoteeEmail: "報價者電郵",
    companyName: "公司名稱",
    district: "區",
    days: "天",
    street: "街道",
    floorUnit: "樓層單位",
    startDate: "開始日期:",
    endDate: "結束日期:",
    candidateMaterials: "候選材料",
    confirmationRecord: "確認記錄",
    variableOrder: "可變訂單",
    milestone: "里程碑",
    defects: "缺陷",
    contact: "聯絡人",
    placeholder: "任務描述",
    noneTasks: "沒有可用的任務.",
    addTask: "添加任務",
    modalTitleTask: "添加任務",
    taskDescription: "任務描述：",
    errorNoSelect2: "請選擇至少一個有數量的產品.",
    ownerName: "擁有者名稱:",
    projectDetails: "項目詳情",
    tel: "電話:",
    modalTitleCategory: "添加類別",
    modalPlaceholderCategory: "輸入類別名稱",
    modalConfirmCategory: "確認",
    modalCancelCategory: "取消",
    progress: "進度",
    blueprint: "藍圖",
    beforePic: "維修前照片",
    afterPic: "維修後照片",
    defectStatus: "缺陷狀態",
  },
};

export default words;
